### ISSUE TITLE
How to decrease speed of the particles?

### ISSUE THREAD

**Issue by Matthias-Mosthof** [Joepocalyptic/nuxt-particles#14]
Is it possible? Dont see anything in the documentation.

**Comment by Matthias-Mosthof** [comment]
Ah, I just found the right Documentation sorry.

**Comment by Joepocalyptic** [comment]
I'll add a link to the documentation of the base library in the readme!

**Comment by Matthias-Mosthof** [comment]
okay that would be perfect :)
