### ISSUE TITLE
Problems with interactivity

### ISSUE THREAD

**Issue by Davekeel** [Joepocalyptic/nuxt-particles#18]
Hi, i installed this on nuxt, anche i noticed some of options with interactivity that works on TsParticles with nuxt-particles doesn't work, here are my options,
`const options = {
  fps_limit: 60,
  background: {
    color: '#f5f5f5'
  },
  fullScreen: {
    enable: true,
    zIndex: 0,
  },
  interactivity: {
    detect_on: 'canvas',
    events: {
      onhover: {
        enable: true,
        mode: 'repulse',
        type: 'rectangle'
      },
      resize: true
    },
    modes: {
      bubble: {
        distance: 400,
        duration: 2,
        opacity: 0.8,
        size: 5,
        speed: 3,
        color: ['#005082', '#005082']
      }
    }
  },
  particles: {
    color: {
      value: [
        ['#05a3d7', '#05a3d7'],
        ['#005082', '#005082']
      ]
    },
    links: {
      color: 'random',
      distance: 220,
      enable: true,
      opacity: 0.4,
      width: 1
    },
    move: {
      collisions: true,
      direction: 'none',
      enable: true,
      out_mode: 'bounce',
      random: false,
      speed: 0.5,
      straight: false
    },
    number: { 
      density: { 
        enable: true, 
        value_area: 1800 
      }, 
      value: 150 
    },
    opacity: {
      animation: { 
        enable: false, 
        minimumValue: 0.1, 
        speed: 1, 
        sync: false 
      },
      random: false,
      value: 1
    },
    shape: {
      type: 'circle'
    },
    size: {
      animation: {
        enable: true,
        minimumValue: 8,
        speed: 1,
        sync: false
      },
      random: {
        enable: true,
        minimumValue: 8
      },
      value: 4
    }
  },
  retina_detect: true
}`

I noticed that my bubbles doesnt repulse, someone can help me?

**Comment by Joepocalyptic** [comment]
This module is now using tsparticles v3, which changed how some of the settings work. Notably, I'm pretty sure all options now use camelCase, as shown here:
![SmartSelect_20240328_082429_Chrome.png](https://github.com/Joepocalyptic/nuxt-particles/assets/42530725/707ece17-6afd-4390-9e9d-1967c1728973)

I would check out the [main repo](https://github.com/tsparticles/tsparticles) for more information.

**Comment by Joepocalyptic** [comment]
Documentation for the `interactivity` object is also available here: https://particles.js.org/docs/interfaces/tsParticles_Engine.Options_Interfaces_Interactivity_IInteractivity.IInteractivity.html

**Comment by Davekeel** [comment]
Thank you! U saved my day!
