### ISSUE TITLE
Error after Upgrade

### ISSUE THREAD

**Issue by ghost** [Joepocalyptic/nuxt-particles#24]
After upgrading all to newest version, in development mode, the particles destroy my site.

Can anyone help me with this issue? 
I don't want to miss the very nice particle effect...

):

error example:

The tsparticles-engine module or its type declarations were not found.

`npm WARN deprecated tsparticles-plugin-easing-quad@2.12.0: starting from tsparticles v3 the packages are now moved to @tsparticles/package-name instead of tsparticles-package-name`

**Comment by ghost** [comment]
delting of background solved it!


``background: {
  color: {
    value: '#0A0F0F'
  }
},``

**Comment by Joepocalyptic** [comment]
It looks like the error you were getting was related to importing packages from tsparticles v2; this module now uses tsparticles v3. I'd double check your deps/imports to ensure you're getting packages from under the `@tsparticles` scope.

**Comment by ghost** [comment]
Yes I see.

``import type { Container } from '@tsparticles/engine';``

**Comment by ghost** [comment]
Deleting of ``background: { color: { value: '#0A0F0F' } },``is also required to ensure successful view on my website.

**Comment by Joepocalyptic** [comment]
What's happening when you set the color?

**Comment by danielhill1982** [comment]
Bad things happen to my site if I use background with a unique color.

**Comment by ghost** [comment]
I had to figure it out to run it updated. What I now notice is that the animation is in the foreground of images, but it should actually be in the background like the rest of my website.
